"""App tests for the Python/Bash operators example.

After deploy, both workflows are created and run by the manifest's
``workflow.create`` / ``workflow.run`` bootstrap actions. These tests use the
MWAA Serverless API to confirm each workflow exists and that its most recent run
reached the SUCCESS state, which proves the operator code package (the .zip for
the PythonOperator and the .sh for the BashOperator) was uploaded and executed.

Tests use the ``smus_config`` fixture auto-generated by ``smus-cli test`` with
the target project's connection details.
"""

import os

import boto3
import pytest

_APPLICATION_NAME = "PythonBashOperatorsExample"


def _airflow_serverless_client(region):
    endpoint = os.environ.get(
        "AIRFLOW_SERVERLESS_ENDPOINT",
        f"https://airflow-serverless.{region}.api.aws/",
    )
    return boto3.client("mwaa-serverless", region_name=region, endpoint_url=endpoint)


@pytest.fixture(scope="module")
def region(smus_config):
    return smus_config.get("region", os.environ.get("DOMAIN_REGION", "us-east-1"))


@pytest.fixture(scope="module")
def project_name(smus_config):
    # The test project the manifest deploys to.
    return smus_config.get("project_name", "test-marketing")


def _find_workflow_arn(client, full_name):
    next_token = None
    for _ in range(20):
        kwargs = {"MaxResults": 50}
        if next_token:
            kwargs["NextToken"] = next_token
        resp = client.list_workflows(**kwargs)
        for wf in resp.get("Workflows", []):
            if wf["Name"] == full_name:
                return wf["WorkflowArn"]
        next_token = resp.get("NextToken")
        if not next_token:
            break
    return None


def _assert_workflow_succeeded(region, project_name, workflow_name):
    full_name = f"{_APPLICATION_NAME}_{project_name}_{workflow_name}"
    client = _airflow_serverless_client(region)

    arn = _find_workflow_arn(client, full_name)
    assert arn is not None, f"Workflow not found: {full_name}"

    runs = client.list_workflow_runs(WorkflowArn=arn, MaxResults=10).get(
        "WorkflowRuns", []
    )
    assert runs, f"No runs found for workflow {full_name}"

    # Most recent run should have completed successfully.
    latest = runs[0]
    run = client.get_workflow_run(WorkflowArn=arn, RunId=latest["RunId"])
    state = run.get("RunDetail", {}).get("RunState")
    assert state == "SUCCESS", (
        f"Workflow {full_name} latest run state is {state}, expected SUCCESS"
    )
    print(f"✅ {full_name} ran successfully")


def test_python_operator_workflow_succeeded(region, project_name):
    """PythonOperator workflow ran its .zip code package successfully."""
    _assert_workflow_succeeded(region, project_name, "python_operator_workflow")


def test_bash_operator_workflow_succeeded(region, project_name):
    """BashOperator workflow ran its .sh code file successfully."""
    _assert_workflow_succeeded(region, project_name, "bash_operator_workflow")
